MVC5_Do_an/Wool.Web/Areas/Admin/ViewModels/SupplierViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wool.Web.Areas.Admin.ViewModels
{
    public class SupplierViewModel
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}

MVC5_Do_an/Wool.Web/ViewModels/SupplierViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wool.Web.ViewModels
{
    public class SupplierViewModel
    {
        public long Id { get; set; }
        public string Name { get; set; }
    }
}

MVC5_Do_an/Wool.Web/Areas/Admin/Controllers/SupplierController.cs
using AutoMapper;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Wool.Model;
using Wool.Service;
using Wool.Web.ViewModels.Admin;

namespace Wool.Web.Areas.Admin.Controllers
{
    public class SupplierController : Controller
    {
        private readonly ISupplierService supplierService;

        public SupplierController(ISupplierService supplierService)
        {
            this.supplierService = supplierService;
        }


        // GET: Admin/Supplier
        public ActionResult Index()
        {
            var vmSupplier = new AdminSupplierViewModel();

            IEnumerable<AdminSupplierViewModel> viewModelSuppliers;
            IEnumerable<Supplier> suppliers;

            suppliers = supplierService.GetSuppliers().ToList();

            ViewBag.Items = Mapper.Map<IEnumerable<Supplier>, IEnumerable<AdminSupplierViewModel>>(suppliers);

            return View(vmSupplier);
        }

        public ActionResult Insert(AdminSupplierViewModel newSupplier)
        {
            if (newSupplier != null)
            {
                var file = Request.Files["upLogo"];
                if (file.ContentLength > 0)
                {
                    newSupplier.Logo = file.FileName;
                    file.SaveAs(Server.MapPath("~/images/suppliers/" + file.FileName));
                }
                else
                {
                    newSupplier.Logo = "Supplier.png";
                }

                var supplier = Mapper.Map<AdminSupplierViewModel, Supplier>(newSupplier);
                supplierService.CreateSupplier(supplier);
                supplierService.SaveSupplier();
                ModelState.Clear();
            }
            var suppliers = supplierService.GetSuppliers().ToList();
            ViewBag.Items = Mapper.Map<IEnumerable<Supplier>, IEnumerable<AdminSupplierViewModel>>(suppliers);

            return View("Index");
        }

        public ActionResult Edit(long id)
        {
            var supplier = supplierService.GetSupplierByID(id);
            var suppliers = supplierService.GetSuppliers().ToList();
            ViewBag.Items = Mapper.Map<IEnumerable<Supplier>, IEnumerable<AdminSupplierViewModel>>(suppliers);
            var supplierViewModel = Mapper.Map<Supplier, AdminSupplierViewModel>(supplier);
            return View("Index", supplierViewModel);
        }

        public ActionResult Delete(long id)
        {
            var supplier = supplierService.GetSupplierByID(id);
            var supplierViewModel = Mapper.Map<Supplier, AdminSupplierViewModel>(supplier);
            try
            {
                supplierService.DeleteSupplier(supplier);
                supplierService.SaveSupplier();
                ModelState.Clear();
                ModelState.AddModelError("", "Xóa thành công !");
                var suppliers = supplierService.GetSuppliers().ToList();
                ViewBag.Items = Mapper.Map<IEnumerable<Supplier>, IEnumerable<AdminSupplierViewModel>>(suppliers);
                return View("Index");
            }
            catch
            {
                ModelState.AddModelError("", "Xóa thất bại !");
                return View("Index", supplierViewModel);
            }
        }

        public ActionResult Update(AdminSupplierViewModel updatedSupplier)
        {
            try
            {
                var file = Request.Files["upLogo"];
                if (file.ContentLength > 0)
                {
                    updatedSupplier.Logo = file.FileName;
                    file.SaveAs(Server.MapPath("~/images/suppliers/" + file.FileName));
                }
                var supplier = Mapper.Map<AdminSupplierViewModel, Supplier>(updatedSupplier);
                supplierService.UpdateSupplier(supplier);
                supplierService.SaveSupplier();
                ModelState.AddModelError("", "Cap nhat thành công !");
            }
            catch
            {
                ModelState.AddModelError("", "Cap nhat thất bại !");
            }
            var suppliers = supplierService.GetSuppliers().ToList();
            ViewBag.Items = Mapper.Map<IEnumerable<Supplier>, IEnumerable<AdminSupplierViewModel>>(suppliers);
            return View("Index");
        }
    }
}

MVC5_Do_an/Wool.Web/Areas/Admin/Views/Supplier/Index.cshtml
@model Wool.Web.ViewModels.Admin.AdminSupplierViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Supplier Manager</h2>

<div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#edit" aria-controls="home" role="tab" data-toggle="tab">
                <span class="glyphicon glyphicon-edit"></span>
                Edition
            </a>
        </li>
        <li role="presentation">
            <a href="#list" aria-controls="profile" role="tab" data-toggle="tab">
                <span class="glyphicon glyphicon-list"></span>
                List
            </a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="edit">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-briefcase"></span>
                        Supplier Edition
                    </h3>
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm("Index", "Supplier", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        if (!Html.ValidationSummary().ToString().Contains(":none"))
                        {
                            <div class="pull-right label label-danger">

                                @Html.ValidationSummary()

                            </div>
                        }
                        <div class="form-group">
                            <label>Id</label>
                            @Html.TextBoxFor(m => m.Id, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label>Name</label>
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label>Logo</label>
                            <input type="file" name="upLogo" />
                            @Html.HiddenFor(m => m.Logo, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label>Phone</label>
                            @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <div class="text-center btn-crud">
                                <button class="btn btn-default" data-action="Insert">Insert</button>
                                <button class="btn btn-default" data-action="Update">Update</button>
                                <button class="btn btn-default" data-action="Delete">Delete</button>
                                <button class="btn btn-default" data-action="Index">Reset</button>
                            </div>
                            <script>
                                $(function () {
                                    $("button[data-action]").click(function () {
                                        var action = $(this).attr("data-action");
                                        this.form.action = "/Admin/Supplier/" + action;
                                    });
                                });
                            </script>
                        </div>
                    }
                </div>
                <div class="panel-footer"></div>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="list">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-briefcase"></span>
                        Supplier List
                    </h3>
                </div>
                <table class="table table-hover table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Logo</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var Item in ViewBag.Items)
                        {
                            <tr>
                                <td>@Item.Id</td>
                                <td>@Item.Name</td>
                                <td>@Item.Email</td>
                                <td>@Item.Phone</td>
                                <td>@Item.Logo</td>
                                <td>
                                    <a class="btn btn-sm btn-danger" href="/Admin/Supplier/Edit/@Item.Id"><span class="glyphicon glyphicon-edit"></span></a>
                                    <a class="btn btn-sm btn-warning" href="/Admin/Supplier/Delete/@Item.Id"><span class="glyphicon glyphicon-trash"></span></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>